version: "3.9"
services:

  chat-app:
    image: chatapp:0.1.0-SNAPSHOT
    container_name: chat-app
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - DB_HOST=postgres
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    restart: always
    image: "postgres:14.4"
    container_name: chat-app-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=chats